[package]
name = "adoption_test"
version = "0.1.0"
authors = ["Christian Legnitto <christian@legnitto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = "=0.3.0-alpha.16"
